/// Flutter icons RiskDiceRoller
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RiskDiceRoller
///      fonts:
///       - asset: fonts/RiskDiceRoller.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RiskDiceRoller {
  RiskDiceRoller._();

  static const _kFontFam = 'RiskDiceRoller';
  static const String? _kFontPkg = null;

  static const IconData dicesRandomNot = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dicesRandom = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
